spring:
  application:
    name: PigeonSkyRace

  datasource:
    postgresql:
      jdbc-url: jdbc:postgresql://localhost:5432/pigeonSky
      username: postgres
      password: user
      driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/pigeon_competition_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

logging:
  level:
    root: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.jdbc: DEBUG

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    postgresql:
      jdbc-url: jdbc:postgresql://localhost:5432/pigeonSky
  data:
    mongodb:
      uri: mongodb://dev-server:27017/dev_pigeon_competition